enum routes {
	HOME = "HOME",
	CHAT = "CHAT",
	SUGGESTIONS = "SUGGESTIONS",
	HOME_TAB = "HOME_TAB",
	GENERAL_CHAT_TAB = "GENERAL_CHAT_TAB",
	LANGUAGE_SECTION = "Language",
	CODING_INNER_SECTION = "CODING_INNER_SECTION",
	COOKING_INNER_SECTION = "COOKING_INNER_SECTION",
}

export default routes;
