enum routes {
	HOME = "HOME",
	CHAT = "CHAT",
	SUGGESTIONS = "SUGGESTIONS",
	HOME_TAB = "HOME_TAB",
	GENERAL_CHAT_TAB = "GENERAL_CHAT_TAB",
	INGREDIENTS = "INGREDIENTS",
	SECTION_INNER_SECTION = "SECTION_INNER_SECTION",
}

export default routes;
