enum SectionType {
	HEALTH = "Health",
	FITNESS = "Fitness",
	LANGUAGE = "Language",
	LANGUAGE_CONVERTER = "Language Converter",
	LANGUAGE_COVER_LETTER = "Cover Letter",
	LANGUAGE_SUMMARIZE = "Summarize",
	LANGUAGE_ESSAY = "Essay",
	LANGUAGE_REPHRASE = "Rephrase",
	LANGUAGE_GRAMMARLY = "Grammarly",
	CODING = "Coding",
	CODING_DSA = "CODING_DSA",
	CODING_ERROR_FINDER = "CODING_ERROR_FINDER",
	CODING_CODE_OPTIMIZATION = "CODING_CODE_OPTIMIZATION",
	CODING_WEBSITE_TEMPLATE = "CODING_WEBSITE_TEMPLATE",
	COOKING = "Cooking",
	COOKING_RECIPE = "COOKING_RECIPE",
	COOKING_DISH_GENERATOR = "COOKING_DISH_GENERATOR",
	HISTORY = "HISTORY",
	QUERY = "QUERY",
	TRAVEL = "TRAVEL",
}

export default SectionType;
